config/routes.rb
DBCForum::Application.routes.draw do

  resources :users, except: [:index, :destroy]

  resources :questions, except: [:edit, :update, :destroy] do
    resources :answers, only: [:create]
  end

  root :to => 'sessions#index'

  get 'login' => 'sessions#new', :as => 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  patch '/about/:id' => 'users#update', :as => 'about'
  post '/answers/:answer_id/votes/:vote', to: 'votes#create'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :id, :question_id, :responder_id, :body

  belongs_to :question
  belongs_to :responder, class_name: "User"
  has_many :votes

  # validates :question, presence: true

  def vote_score
  	@upvotes = self.votes.where("state = ?", 1).count 		# 3
  	@downvotes = self.votes.where("state = ?", 0).count	# 1
  	vote_score = @upvotes - @downvotes
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :asker, class_name: "User"
  has_many :answers
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  attr_accessor :tag_names

  attr_accessible :title, :body, :asker_id, :tag_names

  validates :title, :presence => true
  validates :body, :presence => true
  validates :asker_id, :presence => true

  after_save :assign_tags

  def ordered_answers
    @answers = self.answers.sort_by! { |answer| answer.vote_score }
    @answers.reverse
  end

  private

  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/, /).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings, :dependent => :destroy
  has_many :questions, :through => :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
  
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :email, :password, :password_confirmation, :about

	has_secure_password

  has_many :questions, foreign_key: :asker_id
  has_many :votes, foreign_key: :voter_id
  has_many :answers, foreign_key: :responder_id

  validates :password, presence: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	attr_accessible :answer_id, :voter_id, :state
  belongs_to :answer
  belongs_to :voter, class_name: "User"
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.create!(body: params[:answer][:body], question_id: params[:question_id], responder_id: current_user.id  )
    redirect_to question_path(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper
  # include ActionController::Caching
  # self.page_cache_directory = Rails.public_path
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    if session[:user_id]  # doesn't work with current_user method could be bug in controller_spec
      render 'new'
    else
      flash[:error] = "You must be logged in to create a question."
      redirect_to root_path
    end
  end

  def create
    @question = current_user.questions.build(params[:question])

    if @question.save
      redirect_to question_path(@question)
    else
      redirect_to new_question_path
    end
  end

  def show
    if Question.where("id = ?", params[:id]).length == 0
      redirect_to root_path
    else
      @question = Question.find(params[:id])
      @answers = @question.ordered_answers
    end
  end

  # def question_params
  #   params.require(:question).permit(:title, :text)
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @questions = Question.store_question
    @user = User.find_by_id(params[:user_id])
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      flash[:success] = "Successful signin"
      session[:user_id] = user.id
      redirect_to "/users/#{user.id}"
    else
      flash[:error] = "Email or password incorrect."
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def new
		@user = User.new()
	end

	def create
		@user = User.new(params[:user])
		@user.password_confirmation = params[:user][:password_confirmation]

		if @user.save!
			flash[:success] = "New User Created"
			session[:user_id] = @user.id
			render :about
		else
			flash[:error] = "User not Created"
			redirect_to("/users/new")
		end
	end

	# def user_parameters
	# 	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	# end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update

		@user = User.find(params[:id])
		@user.update_columns(params[:user])
		redirect_to user_path(@user)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create

    # Used for redirecting back to the quesiton.
    current_a = Answer.find(params[:answer_id])

    if vote_exist?(params[:answer_id])
      vote = Vote.find_by_answer_id_and_voter_id(params[:answer_id], session[:user_id])
      vote.update(state: params[:vote])
      redirect_to question_path(current_a.question_id)

    else
      Vote.create(answer_id: params[:answer_id], voter_id: session[:user_id], state: params[:vote])
      redirect_to question_path(current_a.question_id)
    end

  end

  def vote_exist?(a)
    Vote.exists?(answer_id: a, voter_id: session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
    if User.exists?(session[:user_id])
		  return User.find(session[:user_id])
    end
    
    return false
	end

	def flash_class(level)
		case level
		when :success then "success"
		when :error then "error"
		end
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DBCForum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <div class='nav_content'>
    <div class='left-align'>
      <%= link_to 'DBCForum', root_path %>
      <%= link_to "Ask a Question", new_question_path %>
    </div>
      <% if current_user %>
        <div class='right-align'>
        <%= link_to "Account", edit_user_path(@user) %>
        <%= link_to current_user.name + "'s profile", user_path(current_user) %>
        <%= link_to 'Log out', logout_path %>
        </div>
      <% else %>
        <div class='right-align'>
        <%= link_to 'Log in', login_path %>
        <%= link_to 'Sign up', new_user_path %>
        </div>
      <% end %>
  </div>

</nav>

<%= yield %>

<div class="content-div">

  <% if flash[:success] %>
    <p class="flash"><%= flash[:success]  %></p>
  <% elsif flash[:error] %>
    <p class="bad-flash"><%= flash[:error] %></p>
  <% end %>

</div>

</body>
</html>

app/views/questions/new.html.erb
<div class="content-div">
<h1>Create a new question!</h1>

<%= form_for :question, url: questions_path do |form_builder| %>
  <p>
    <%= form_builder.label :title %><br>
    <%= form_builder.text_field :title %>
  </p>

  <p>
    <%= form_builder.label :body %><br>
    <%= form_builder.text_area :body %>
  </p>

  <p>
    <%= form_builder.label :tag_names %><br>
    <%= form_builder.text_field :tag_names %>
  </p>

  <p>
    <%= form_builder.submit %>
  </p>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="content-div">
  <div class='question-page'>

  <%# cache do %>
    <h1><%= @question.title %></h1>
    <h4>Written by: <%= @question.asker.name %></h4>

    <p><%= @question.body %></p>

    <h2>Answers</h2>
  <%# end %>
  <ul>
      <% @answers.each do |answer| %>
      <li><%= answer.body %><br>
        <a href="/users/<%= answer.responder.id %>"><%= answer.responder.name %></a></li>
        <br>
          <li><%= button_to "Upvote", "/answers/#{answer.id}/votes/1", method: 'post' %>
          <p><%= answer.vote_score%></p>
          <%= button_to "Downvote", "/answers/#{answer.id}/votes/0", method: 'post' %></li><br><br>
      <% end %>
  </ul>

  <% if current_user %>
    <%= form_for :answer, url: question_answers_path(@question) do |f| %>
      <%= f.text_area(:body, rows: 10, cols: 30) %>
      <%= f.submit %>
    <% end %>
  <% end %>

  </div>
</div>

app/views/users/_signup_form.html.erb
<%= form_for(@user) do |f| %>
	<%= f.label :name%>
	<%= f.text_field :name, :autofocus => true %><br>

	<%= f.label :email %>
	<%= f.email_field :email %><br>

	<%= f.label :password, 'Password' %>
	<%= f.password_field :password %><br>

 	<%= f.label :password_confirmation, 'Confirm Password' %>
	<%= f.password_field :password_confirmation %><br>
	<%= f.submit %>
	<% end %>

app/views/users/about.html.erb
<div class="content-div">
  <h2> Tell us something quirky about yourself </h2>

  <%= form_for(@user, url: about_path(@user)) do |f| %>
    
    <%= f.label :about %>
    <%= f.text_area(:about,  rows: 10, cols: 30) %>

    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="content-div">
  <%= form_for(@user) do |f| %>
    <%= f.label :name, :autofocus => true%>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :about %>
    <%= f.text_area(:about,  rows: 10, cols: 30) %>

    <%= f.submit %>

  <% end %>
</div>

app/views/users/new.html.erb
<div class="content-div">
  <%= form_for @user do |f| %>

  	<%= f.label :name%>
  	<%= f.text_field :name, :autofocus => true %>

  	<%= f.label :email %>
  	<%= f.email_field :email, :required => true %>
    
    <%#= f.label :about %>
    <%#= f.text_area(:about,  rows: 10, cols: 30) %>

  	<%= f.label :password, 'Password' %>
  	<%= f.password_field :password, :required => true %>

   	<%= f.label :password_confirmation, 'Confirm Password' %>
  	<%= f.password_field :password_confirmation, :required => true %>
  	<%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="content-div">
  <div class='two-column'>
    <% cache('user_bio') do %>
      <h1><%= @user.name %>'s Profile Page</h1>
      <h3>Email: <%= @user.email %></h3>
      <p> <%= @user.about %> </p>
    </div>
  <% end %>

  <% if @user.questions[0] %>
    <div class='column-left'>
    <h2>Questions <%= @user.name %> Asked:</h2>
      <ul>
        <% @user.questions.each do |question| %>
        <li>
          <%= link_to question.title, question_path(question) %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.answers[0] %>
    <div class='column-right'>
    <h2>Questions <%= @user.name %> Answered:</h2>
      <ul>
        <% @user.answers.each do |answer| %>
          <% author = answer.question.asker.name %>

          <h3><%= answer.question.title %></h3>
          <!-- <h4>by <%#= author %></h4> -->

        <li>
          <%= link_to answer.body, question_path(answer.question) %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>